apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-aws
data:
  credentials: |
    aws_access_key_id = AKIAQU7O3R2DWLDN54U6
    aws_secret_access_key = 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

                            